課題提出
nsc-g-inagaki/Dx- pull request #10
Opened 2021-02-06 11:00 UTC by y-moroto

課題がすべて完了しましたので、提出致します。
ご確認の程お願い致します。

2021-02-09 05:22 UTC, nsc-g-inagaki commented on python/challenge1.py
> +    print("a / b =",math.floor(a / b),"（小数点以下切り捨て）")
切り捨て計算は、mathライブラリなしでもできますよ。

目的が果たせているので、修正・再提出はいらないです。

2021-02-09 05:22 UTC, nsc-g-inagaki commented on python/challenge1.py
> +    #calenderライブラリのisleap関数を使うのは反則でしょうか・・・？
calendarライブラリのisleap関数が同じ条件を使っているのであれば使っても問題ないですよ

2021-02-12 05:13 UTC, nsc-g-inagaki requested changes

2021-02-12 05:13 UTC, nsc-g-inagaki commented on SQL/scripts/challenge2.sql
> +LIMIT 5;
このクエリですと、面積が最も大きい国トップ5が表示されます。

各大陸ごとに面積の大きいトップ5が表示されるように修正してください。

2021-02-13 02:31 UTC, y-moroto commented on SQL/scripts/challenge2.sql
> +LIMIT 5;
大変失礼致しました。修正致しましたので、再度ご確認をお願いいたします。

2021-02-24 11:05 UTC, nsc-g-inagaki commented
修正確認しました、ばっちりですね！

2021-02-24 11:05 UTC, closed without merging